#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream

on:
  push:
    branches: 
      - zzq
  schedule:
    - cron: 30 19 * * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
          git config user.name zhiqiang.zhou@osr-tech.com
          git config user.email zhiqiang.zhou@osr-tech.com

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: zzq
      run: git push origin $DOWNSTREAM_BRANCH
